name: flutter_midi_command
description: A Flutter plugin for sending and receiving MIDI messages between Flutter and physical and virtual MIDI devices. Wraps CoreMIDI and android.media.midi in a thin dart/flutter layer.
publish_to: none
version: 0.5.4
homepage: https://github.com/renanyoy/FlutterMidiCommand

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface: 
    git: https://github.com/renanyoy/flutter_midi_command_platform_interface.git
    
dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  config:
    enable-swift-package-manager: true
  plugin:
    platforms:
      android:
        package: com.invisiblewrench.fluttermidicommand
        pluginClass: FlutterMidiCommandPlugin
      ios:
        pluginClass: FlutterMidiCommandPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: FlutterMidiCommandPlugin
        sharedDarwinSource: true


